//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownUtilityBillSystemV2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TownUtilityBillSystemV2.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Thomas Thune Andersen, Chairman of the Board of Directors, said: “DONG was originally short for Danish Oil and Natural Gas. With our profound strategic 
        ///transformation and the divestment of our upstream oil and gas business, this is no longer who we are. Therefore, now is the right time to change our name..
        /// </summary>
        public static string AboutData_ChairmanСitation {
            get {
                return ResourceManager.GetString("AboutData_ChairmanСitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the 6th of November 2017.
        /// </summary>
        public static string AboutData_ChangeNameDate {
            get {
                return ResourceManager.GetString("AboutData_ChangeNameDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7th of August 2017..
        /// </summary>
        public static string AboutData_FirstReleaseDate {
            get {
                return ResourceManager.GetString("AboutData_FirstReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has changed name to.
        /// </summary>
        public static string AboutData_HasChangedNameTo {
            get {
                return ResourceManager.GetString("AboutData_HasChangedNameTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is a web application that helps to manage by the data for the town utility services such as the electricity, the water, the heating and the gas. Also it operates by the customer bill system..
        /// </summary>
        public static string AboutData_IsAWebAppThatHelps {
            get {
                return ResourceManager.GetString("AboutData_IsAWebAppThatHelps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is one of Northern Europe&apos;s leading energy groups and is headquartered in Denmark. Around 6,500 ambitious employees develop, construct and operate offshore wind farms, generate power and heat from our power	stations as well as supply and trade in energy to wholesale, business and residential customers. In addition, we produce oil and gas, and a process has been initiated to divest this business unit. The continuing part of the Group has approx 6,100 employees
        ///and generated a revenue in 2016 of DKK 61 billi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutData_IsOneOfNorthernEurope {
            get {
                return ResourceManager.GetString("AboutData_IsOneOfNorthernEurope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first release of the App was on the.
        /// </summary>
        public static string AboutData_TheFirstRelease {
            get {
                return ResourceManager.GetString("AboutData_TheFirstRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account #.
        /// </summary>
        public static string AccountNum {
            get {
                return ResourceManager.GetString("AccountNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative building.
        /// </summary>
        public static string AdministrativeBuilding {
            get {
                return ResourceManager.GetString("AdministrativeBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin will be notified..
        /// </summary>
        public static string AdminWillBeNotified {
            get {
                return ResourceManager.GetString("AdminWillBeNotified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All customers.
        /// </summary>
        public static string AllCustomers {
            get {
                return ResourceManager.GetString("AllCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All meter types.
        /// </summary>
        public static string AllMeterTypes {
            get {
                return ResourceManager.GetString("AllMeterTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All news.
        /// </summary>
        public static string AllNews {
            get {
                return ResourceManager.GetString("AllNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Utilities.
        /// </summary>
        public static string AllUtilities {
            get {
                return ResourceManager.GetString("AllUtilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All utility meters.
        /// </summary>
        public static string AllUtilityMeters {
            get {
                return ResourceManager.GetString("AllUtilityMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment.
        /// </summary>
        public static string Apartment {
            get {
                return ResourceManager.GetString("Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average temperature per year.
        /// </summary>
        public static string AverageTemperaturePerYear {
            get {
                return ResourceManager.GetString("AverageTemperaturePerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to home page.
        /// </summary>
        public static string BackToHomePage {
            get {
                return ResourceManager.GetString("BackToHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to main menu.
        /// </summary>
        public static string BackToMainMenu {
            get {
                return ResourceManager.GetString("BackToMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to previous page.
        /// </summary>
        public static string BackToPreviousPage {
            get {
                return ResourceManager.GetString("BackToPreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance before this bill.
        /// </summary>
        public static string BalanceBeforeThisBill {
            get {
                return ResourceManager.GetString("BalanceBeforeThisBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill.
        /// </summary>
        public static string Bill {
            get {
                return ResourceManager.GetString("Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill charges.
        /// </summary>
        public static string BillCharges {
            get {
                return ResourceManager.GetString("BillCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill data.
        /// </summary>
        public static string BillData {
            get {
                return ResourceManager.GetString("BillData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill date.
        /// </summary>
        public static string BillDate {
            get {
                return ResourceManager.GetString("BillDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing date.
        /// </summary>
        public static string BillingDate {
            get {
                return ResourceManager.GetString("BillingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill #.
        /// </summary>
        public static string BillNum {
            get {
                return ResourceManager.GetString("BillNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill number.
        /// </summary>
        public static string BillNumber {
            get {
                return ResourceManager.GetString("BillNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill period.
        /// </summary>
        public static string BillPeriod {
            get {
                return ResourceManager.GetString("BillPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bills.
        /// </summary>
        public static string Bills {
            get {
                return ResourceManager.GetString("Bills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill sum.
        /// </summary>
        public static string BillSum {
            get {
                return ResourceManager.GetString("BillSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        public static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building image.
        /// </summary>
        public static string BuildingImage {
            get {
                return ResourceManager.GetString("BuildingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cafe.
        /// </summary>
        public static string Cafe {
            get {
                return ResourceManager.GetString("Cafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate the charges.
        /// </summary>
        public static string CalculateCharges {
            get {
                return ResourceManager.GetString("CalculateCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculations.
        /// </summary>
        public static string Calculations {
            get {
                return ResourceManager.GetString("Calculations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator on-line.
        /// </summary>
        public static string CalculatorOnLine {
            get {
                return ResourceManager.GetString("CalculatorOnLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The card is expired..
        /// </summary>
        public static string CardIExpired {
            get {
                return ResourceManager.GetString("CardIExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card owner: name.
        /// </summary>
        public static string CardOwnerName {
            get {
                return ResourceManager.GetString("CardOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card owner: surname.
        /// </summary>
        public static string CardOwnerSurname {
            get {
                return ResourceManager.GetString("CardOwnerSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card type.
        /// </summary>
        public static string CardType {
            get {
                return ResourceManager.GetString("CardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges.
        /// </summary>
        public static string Charges {
            get {
                return ResourceManager.GetString("Charges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check utility name.
        /// </summary>
        public static string CheckUtilityName {
            get {
                return ResourceManager.GetString("CheckUtilityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the next facility.
        /// </summary>
        public static string ChooseNextFacility {
            get {
                return ResourceManager.GetString("ChooseNextFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Church.
        /// </summary>
        public static string Church {
            get {
                return ResourceManager.GetString("Church", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match.
        /// </summary>
        public static string ConfirmPasswordWarning {
            get {
                return ResourceManager.GetString("ConfirmPasswordWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumed.
        /// </summary>
        public static string Consumed {
            get {
                return ResourceManager.GetString("Consumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumption history.
        /// </summary>
        public static string ConsumptionHistory {
            get {
                return ResourceManager.GetString("ConsumptionHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the new bill.
        /// </summary>
        public static string CreateNewBill {
            get {
                return ResourceManager.GetString("CreateNewBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the new customer.
        /// </summary>
        public static string CreateNewCustomer {
            get {
                return ResourceManager.GetString("CreateNewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the new meter.
        /// </summary>
        public static string CreateNewMeter {
            get {
                return ResourceManager.GetString("CreateNewMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the new meter data.
        /// </summary>
        public static string CreateNewMeterData {
            get {
                return ResourceManager.GetString("CreateNewMeterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the new meter type.
        /// </summary>
        public static string CreateNewMeterType {
            get {
                return ResourceManager.GetString("CreateNewMeterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the new utility.
        /// </summary>
        public static string CreateNewUtility {
            get {
                return ResourceManager.GetString("CreateNewUtility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Credit card number must have 16 digits..
        /// </summary>
        public static string CreditCardNumberMustHave16Digits {
            get {
                return ResourceManager.GetString("CreditCardNumberMustHave16Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current value.
        /// </summary>
        public static string CurrentValue {
            get {
                return ResourceManager.GetString("CurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV number.
        /// </summary>
        public static string CVVnumber {
            get {
                return ResourceManager.GetString("CVVnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CVV number must have 3 digits..
        /// </summary>
        public static string CVVnumberMustHave3Digits {
            get {
                return ResourceManager.GetString("CVVnumberMustHave3Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete bill.
        /// </summary>
        public static string DeleteBill {
            get {
                return ResourceManager.GetString("DeleteBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete customer.
        /// </summary>
        public static string DeleteCustomer {
            get {
                return ResourceManager.GetString("DeleteCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete meter.
        /// </summary>
        public static string DeleteMeter {
            get {
                return ResourceManager.GetString("DeleteMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete meter item.
        /// </summary>
        public static string DeleteMeterItem {
            get {
                return ResourceManager.GetString("DeleteMeterItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete meter type.
        /// </summary>
        public static string DeleteMeterType {
            get {
                return ResourceManager.GetString("DeleteMeterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete utility.
        /// </summary>
        public static string DeleteUtility {
            get {
                return ResourceManager.GetString("DeleteUtility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denmark.
        /// </summary>
        public static string Denmark {
            get {
                return ResourceManager.GetString("Denmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONG Energy.
        /// </summary>
        public static string DongEnergy {
            get {
                return ResourceManager.GetString("DongEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download PDF.
        /// </summary>
        public static string DownloadPdf {
            get {
                return ResourceManager.GetString("DownloadPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit customer.
        /// </summary>
        public static string EditCustomer {
            get {
                return ResourceManager.GetString("EditCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit data.
        /// </summary>
        public static string EditData {
            get {
                return ResourceManager.GetString("EditData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit meter.
        /// </summary>
        public static string EditMeter {
            get {
                return ResourceManager.GetString("EditMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit meter data.
        /// </summary>
        public static string EditMeterData {
            get {
                return ResourceManager.GetString("EditMeterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit meter type.
        /// </summary>
        public static string EditMeterType {
            get {
                return ResourceManager.GetString("EditMeterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit utility.
        /// </summary>
        public static string EditUtility {
            get {
                return ResourceManager.GetString("EditUtility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit utility parameters.
        /// </summary>
        public static string EditUtilityParameters {
            get {
                return ResourceManager.GetString("EditUtilityParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity.
        /// </summary>
        public static string Electricity {
            get {
                return ResourceManager.GetString("Electricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the bill number.
        /// </summary>
        public static string EnterBillNumber {
            get {
                return ResourceManager.GetString("EnterBillNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter utility month usage.
        /// </summary>
        public static string EnterUtilityMonthUsage {
            get {
                return ResourceManager.GetString("EnterUtilityMonthUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        public static string EnterValidEmail {
            get {
                return ResourceManager.GetString("EnterValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid phone.
        /// </summary>
        public static string EnterValidPhone {
            get {
                return ResourceManager.GetString("EnterValidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire date.
        /// </summary>
        public static string ExpireDate {
            get {
                return ResourceManager.GetString("ExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory.
        /// </summary>
        public static string Factory {
            get {
                return ResourceManager.GetString("Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is required.
        /// </summary>
        public static string FieldIsRequired {
            get {
                return ResourceManager.GetString("FieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a non negative number with 2 decimal digits..
        /// </summary>
        public static string FieldMustBeNonNegativeNumber2WithDecDigits {
            get {
                return ResourceManager.GetString("FieldMustBeNonNegativeNumber2WithDecDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a number with 2 decimal digits.
        /// </summary>
        public static string FieldMustBeNumberWith2DecimalDigits {
            get {
                return ResourceManager.GetString("FieldMustBeNumberWith2DecimalDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a number..
        /// </summary>
        public static string FieldMustBeNumeric {
            get {
                return ResourceManager.GetString("FieldMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find bill by details (number, customer, period).
        /// </summary>
        public static string FindBillByDetailsNumberCustomerPeriod {
            get {
                return ResourceManager.GetString("FindBillByDetailsNumberCustomerPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find customer.
        /// </summary>
        public static string FindCustomer {
            get {
                return ResourceManager.GetString("FindCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find meter by address.
        /// </summary>
        public static string FindMeterByAddress {
            get {
                return ResourceManager.GetString("FindMeterByAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find meter by details.
        /// </summary>
        public static string FindMeterByDetails {
            get {
                return ResourceManager.GetString("FindMeterByDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find meters by details.
        /// </summary>
        public static string FindMetersByDetails {
            get {
                return ResourceManager.GetString("FindMetersByDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat #.
        /// </summary>
        public static string FlatNumber {
            get {
                return ResourceManager.GetString("FlatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat/Part.
        /// </summary>
        public static string FlatPart {
            get {
                return ResourceManager.GetString("FlatPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For additional information, please contact.
        /// </summary>
        public static string ForAdditionalInfoPleaseContact {
            get {
                return ResourceManager.GetString("ForAdditionalInfoPleaseContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        public static string Found {
            get {
                return ResourceManager.GetString("Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found 1 bill.
        /// </summary>
        public static string FoundOneBill {
            get {
                return ResourceManager.GetString("FoundOneBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found 1 customer.
        /// </summary>
        public static string FoundOneCustomer {
            get {
                return ResourceManager.GetString("FoundOneCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found 1 meter.
        /// </summary>
        public static string FoundOneMeter {
            get {
                return ResourceManager.GetString("FoundOneMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel station.
        /// </summary>
        public static string FuelStation {
            get {
                return ResourceManager.GetString("FuelStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas.
        /// </summary>
        public static string Gas {
            get {
                return ResourceManager.GetString("Gas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heating.
        /// </summary>
        public static string Heating {
            get {
                return ResourceManager.GetString("Heating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Higher price.
        /// </summary>
        public static string HigherPrice {
            get {
                return ResourceManager.GetString("HigherPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital.
        /// </summary>
        public static string Hospital {
            get {
                return ResourceManager.GetString("Hospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        public static string Hotel {
            get {
                return ResourceManager.GetString("Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House.
        /// </summary>
        public static string House {
            get {
                return ResourceManager.GetString("House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid building id: {0}..
        /// </summary>
        public static string InvalidBuildingIdParam {
            get {
                return ResourceManager.GetString("InvalidBuildingIdParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt.
        /// </summary>
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid meter id: {0}..
        /// </summary>
        public static string InvalidMeterIdParam {
            get {
                return ResourceManager.GetString("InvalidMeterIdParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid street id: {0}..
        /// </summary>
        public static string InvalidStreetIdParam {
            get {
                return ResourceManager.GetString("InvalidStreetIdParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid town id: {0}..
        /// </summary>
        public static string InvalidTownIdParam {
            get {
                return ResourceManager.GetString("InvalidTownIdParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid utility name: {0}..
        /// </summary>
        public static string InvalidUtilityNameParam {
            get {
                return ResourceManager.GetString("InvalidUtilityNameParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is paid.
        /// </summary>
        public static string IsPaid {
            get {
                return ResourceManager.GetString("IsPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinder garden.
        /// </summary>
        public static string KinderGarden {
            get {
                return ResourceManager.GetString("KinderGarden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal customers.
        /// </summary>
        public static string LegalCustomers {
            get {
                return ResourceManager.GetString("LegalCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than.
        /// </summary>
        public static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log_in.
        /// </summary>
        public static string Log_In {
            get {
                return ResourceManager.GetString("Log_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginForApp {
            get {
                return ResourceManager.GetString("LoginForApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in the system.
        /// </summary>
        public static string LogInSystem {
            get {
                return ResourceManager.GetString("LogInSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure date.
        /// </summary>
        public static string MeasureDate {
            get {
                return ResourceManager.GetString("MeasureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter data.
        /// </summary>
        public static string MeterData {
            get {
                return ResourceManager.GetString("MeterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter number.
        /// </summary>
        public static string MeterNumber {
            get {
                return ResourceManager.GetString("MeterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters.
        /// </summary>
        public static string Meters {
            get {
                return ResourceManager.GetString("Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters for this address.
        /// </summary>
        public static string MetersForThisAddress {
            get {
                return ResourceManager.GetString("MetersForThisAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter type.
        /// </summary>
        public static string MeterType {
            get {
                return ResourceManager.GetString("MeterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter types.
        /// </summary>
        public static string MeterTypes {
            get {
                return ResourceManager.GetString("MeterTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter types.
        /// </summary>
        public static string MeterTypesLowerCase {
            get {
                return ResourceManager.GetString("MeterTypesLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * The meter will be verificated next month. {0} years passed after the last verification (was on {1}).
        /// </summary>
        public static string MeterVerificationNote {
            get {
                return ResourceManager.GetString("MeterVerificationNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month average temperature.
        /// </summary>
        public static string MonthAverageTemperature {
            get {
                return ResourceManager.GetString("MonthAverageTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months&apos; usage (year&apos;s history).
        /// </summary>
        public static string MonthsUsageYearHistory {
            get {
                return ResourceManager.GetString("MonthsUsageYearHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Museum.
        /// </summary>
        public static string Museum {
            get {
                return ResourceManager.GetString("Museum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New value.
        /// </summary>
        public static string NewValue {
            get {
                return ResourceManager.GetString("NewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No any bill is found.
        /// </summary>
        public static string NoAnyBillIsFound {
            get {
                return ResourceManager.GetString("NoAnyBillIsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No any customer is found.
        /// </summary>
        public static string NoAnyCustomerIsFound {
            get {
                return ResourceManager.GetString("NoAnyCustomerIsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No any meter is found.
        /// </summary>
        public static string NoAnyMeterIsFound {
            get {
                return ResourceManager.GetString("NoAnyMeterIsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bill is found -- check the number.
        /// </summary>
        public static string NoBillIsFoundWarning {
            get {
                return ResourceManager.GetString("NoBillIsFoundWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nursery.
        /// </summary>
        public static string Nursery {
            get {
                return ResourceManager.GetString("Nursery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ørsted.
        /// </summary>
        public static string Orsted {
            get {
                return ResourceManager.GetString("Orsted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other utilities.
        /// </summary>
        public static string OtherUtilities {
            get {
                return ResourceManager.GetString("OtherUtilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part -.
        /// </summary>
        public static string PartHyphen {
            get {
                return ResourceManager.GetString("PartHyphen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay another bill.
        /// </summary>
        public static string PayAnotherBill {
            get {
                return ResourceManager.GetString("PayAnotherBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paying sum.
        /// </summary>
        public static string PayingSum {
            get {
                return ResourceManager.GetString("PayingSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The paying sum cannot be negative.
        /// </summary>
        public static string PayingSumCanNotBeNegative {
            get {
                return ResourceManager.GetString("PayingSumCanNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment card form.
        /// </summary>
        public static string PaymentCardForm {
            get {
                return ResourceManager.GetString("PaymentCardForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment card number.
        /// </summary>
        public static string PaymentCardNumber {
            get {
                return ResourceManager.GetString("PaymentCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay on-line.
        /// </summary>
        public static string PayOnLine {
            get {
                return ResourceManager.GetString("PayOnLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay on-line bill.
        /// </summary>
        public static string PayOnLineBill {
            get {
                return ResourceManager.GetString("PayOnLineBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay the bill.
        /// </summary>
        public static string PayTheBill {
            get {
                return ResourceManager.GetString("PayTheBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay the bill on-line.
        /// </summary>
        public static string PayTheBillOnLine {
            get {
                return ResourceManager.GetString("PayTheBillOnLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per.
        /// </summary>
        public static string Per {
            get {
                return ResourceManager.GetString("Per", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant.
        /// </summary>
        public static string Plant {
            get {
                return ResourceManager.GetString("Plant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, log in or register.
        /// </summary>
        public static string PleaseLogInOrRegister {
            get {
                return ResourceManager.GetString("PleaseLogInOrRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private customers.
        /// </summary>
        public static string PrivateCustomers {
            get {
                return ResourceManager.GetString("PrivateCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more....
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string RegisterAsNewUser {
            get {
                return ResourceManager.GetString("RegisterAsNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        public static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date.
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        public static string Restaurant {
            get {
                return ResourceManager.GetString("Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salon.
        /// </summary>
        public static string Salon {
            get {
                return ResourceManager.GetString("Salon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School.
        /// </summary>
        public static string School {
            get {
                return ResourceManager.GetString("School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search filter.
        /// </summary>
        public static string SearchFilter {
            get {
                return ResourceManager.GetString("SearchFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select building--.
        /// </summary>
        public static string SelectBuilding {
            get {
                return ResourceManager.GetString("SelectBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select card type--.
        /// </summary>
        public static string SelectCardType {
            get {
                return ResourceManager.GetString("SelectCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select flat/part--.
        /// </summary>
        public static string SelectFlatPart {
            get {
                return ResourceManager.GetString("SelectFlatPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select street--.
        /// </summary>
        public static string SelectStreet {
            get {
                return ResourceManager.GetString("SelectStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select town--.
        /// </summary>
        public static string SelectTown {
            get {
                return ResourceManager.GetString("SelectTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select type--.
        /// </summary>
        public static string SelectType {
            get {
                return ResourceManager.GetString("SelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service station.
        /// </summary>
        public static string ServiceStation {
            get {
                return ResourceManager.GetString("ServiceStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all bills.
        /// </summary>
        public static string ShowAllBills {
            get {
                return ResourceManager.GetString("ShowAllBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all bills for customer.
        /// </summary>
        public static string ShowAllBillsForCustomer {
            get {
                return ResourceManager.GetString("ShowAllBillsForCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all customers.
        /// </summary>
        public static string ShowAllCustomers {
            get {
                return ResourceManager.GetString("ShowAllCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all meters.
        /// </summary>
        public static string ShowAllMeters {
            get {
                return ResourceManager.GetString("ShowAllMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Meter Types.
        /// </summary>
        public static string ShowAllMeterTypes {
            get {
                return ResourceManager.GetString("ShowAllMeterTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all utilities.
        /// </summary>
        public static string ShowAllUtilities {
            get {
                return ResourceManager.GetString("ShowAllUtilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all utility charts.
        /// </summary>
        public static string ShowAllUtilityCharts {
            get {
                return ResourceManager.GetString("ShowAllUtilityCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all utility usage.
        /// </summary>
        public static string ShowAllUtilityUsage {
            get {
                return ResourceManager.GetString("ShowAllUtilityUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show bill.
        /// </summary>
        public static string ShowBill {
            get {
                return ResourceManager.GetString("ShowBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show bill paid info.
        /// </summary>
        public static string ShowBillPaidInfo {
            get {
                return ResourceManager.GetString("ShowBillPaidInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show bills.
        /// </summary>
        public static string ShowBills {
            get {
                return ResourceManager.GetString("ShowBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show calculator on line.
        /// </summary>
        public static string ShowCalculatorOnLine {
            get {
                return ResourceManager.GetString("ShowCalculatorOnLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show charges.
        /// </summary>
        public static string ShowCharges {
            get {
                return ResourceManager.GetString("ShowCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Customer Menu.
        /// </summary>
        public static string ShowCustomerMenu {
            get {
                return ResourceManager.GetString("ShowCustomerMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details for customer.
        /// </summary>
        public static string ShowDetailsForCustomer {
            get {
                return ResourceManager.GetString("ShowDetailsForCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show found bills.
        /// </summary>
        public static string ShowFoundBills {
            get {
                return ResourceManager.GetString("ShowFoundBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show found customers.
        /// </summary>
        public static string ShowFoundCustomers {
            get {
                return ResourceManager.GetString("ShowFoundCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Found Meters.
        /// </summary>
        public static string ShowFoundMeters {
            get {
                return ResourceManager.GetString("ShowFoundMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show legal customers.
        /// </summary>
        public static string ShowLegalCustomers {
            get {
                return ResourceManager.GetString("ShowLegalCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show meter data.
        /// </summary>
        public static string ShowMeterData {
            get {
                return ResourceManager.GetString("ShowMeterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show metertypes for utility.
        /// </summary>
        public static string ShowMeterTypesForUtility {
            get {
                return ResourceManager.GetString("ShowMeterTypesForUtility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show private customers.
        /// </summary>
        public static string ShowPrivateCustomers {
            get {
                return ResourceManager.GetString("ShowPrivateCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show some meters.
        /// </summary>
        public static string ShowSomeMeters {
            get {
                return ResourceManager.GetString("ShowSomeMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show statistic menu.
        /// </summary>
        public static string ShowStatisticMenu {
            get {
                return ResourceManager.GetString("ShowStatisticMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show temperature chart.
        /// </summary>
        public static string ShowTemperatureChart {
            get {
                return ResourceManager.GetString("ShowTemperatureChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the news.
        /// </summary>
        public static string ShowTheNews {
            get {
                return ResourceManager.GetString("ShowTheNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some random bills.
        /// </summary>
        public static string SomeRandomBills {
            get {
                return ResourceManager.GetString("SomeRandomBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some random customers.
        /// </summary>
        public static string SomeRandomCustomers {
            get {
                return ResourceManager.GetString("SomeRandomCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some random meters.
        /// </summary>
        public static string SomeRandomMeters {
            get {
                return ResourceManager.GetString("SomeRandomMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry.
        /// </summary>
        public static string Sorry {
            get {
                return ResourceManager.GetString("Sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, no data.
        /// </summary>
        public static string SorryNoData {
            get {
                return ResourceManager.GetString("SorryNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, no data for this customer meters.
        /// </summary>
        public static string SorryNoDataForThisCustomerMeters {
            get {
                return ResourceManager.GetString("SorryNoDataForThisCustomerMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        public static string Square {
            get {
                return ResourceManager.GetString("Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sq. m..
        /// </summary>
        public static string SquareMeter {
            get {
                return ResourceManager.GetString("SquareMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistic.
        /// </summary>
        public static string Statistic {
            get {
                return ResourceManager.GetString("Statistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Str.
        /// </summary>
        public static string Str {
            get {
                return ResourceManager.GetString("Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature chart.
        /// </summary>
        public static string TemperatureChart {
            get {
                return ResourceManager.GetString("TemperatureChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theatre.
        /// </summary>
        public static string Theatre {
            get {
                return ResourceManager.GetString("Theatre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bill.
        /// </summary>
        public static string TheBill {
            get {
                return ResourceManager.GetString("TheBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total charges.
        /// </summary>
        public static string TotalCharges {
            get {
                return ResourceManager.GetString("TotalCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total customers for this utility.
        /// </summary>
        public static string TotalCustomersForThisUtility {
            get {
                return ResourceManager.GetString("TotalCustomersForThisUtility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total quantity.
        /// </summary>
        public static string TotalQuantity {
            get {
                return ResourceManager.GetString("TotalQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total to pay.
        /// </summary>
        public static string TotalToPay {
            get {
                return ResourceManager.GetString("TotalToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town.
        /// </summary>
        public static string Town {
            get {
                return ResourceManager.GetString("Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town Utility Bill System.
        /// </summary>
        public static string TownUtilityBillSystem {
            get {
                return ResourceManager.GetString("TownUtilityBillSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial imitation.
        /// </summary>
        public static string TrialImitation {
            get {
                return ResourceManager.GetString("TrialImitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        public static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The usage can not be negative.
        /// </summary>
        public static string UsageCanNotBeNegative {
            get {
                return ResourceManager.GetString("UsageCanNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage for standart price.
        /// </summary>
        public static string UsageForStandartPrice {
            get {
                return ResourceManager.GetString("UsageForStandartPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        public static string Utilities {
            get {
                return ResourceManager.GetString("Utilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities charges.
        /// </summary>
        public static string UtilitiesCharges {
            get {
                return ResourceManager.GetString("UtilitiesCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities prices.
        /// </summary>
        public static string UtilitiesPrices {
            get {
                return ResourceManager.GetString("UtilitiesPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities usage.
        /// </summary>
        public static string UtilitiesUsage {
            get {
                return ResourceManager.GetString("UtilitiesUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility.
        /// </summary>
        public static string Utility {
            get {
                return ResourceManager.GetString("Utility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility meters.
        /// </summary>
        public static string UtilityMeters {
            get {
                return ResourceManager.GetString("UtilityMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string ValueMustBeAtLeastCharactersLong {
            get {
                return ResourceManager.GetString("ValueMustBeAtLeastCharactersLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be bigger than {1}..
        /// </summary>
        public static string ValueMustBeBiggerThan {
            get {
                return ResourceManager.GetString("ValueMustBeBiggerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be bigger than 0..
        /// </summary>
        public static string ValueMustBeBiggerThanZero {
            get {
                return ResourceManager.GetString("ValueMustBeBiggerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must have {2} digits..
        /// </summary>
        public static string ValueMustHaveCountDigits {
            get {
                return ResourceManager.GetString("ValueMustHaveCountDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must habe from {2} to {1} characters long..
        /// </summary>
        public static string ValueMustHaveFromToCharactersLong {
            get {
                return ResourceManager.GetString("ValueMustHaveFromToCharactersLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification date.
        /// </summary>
        public static string VarificationDate {
            get {
                return ResourceManager.GetString("VarificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification period.
        /// </summary>
        public static string VarificationPeriod {
            get {
                return ResourceManager.GetString("VarificationPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varification.
        /// </summary>
        public static string Verification {
            get {
                return ResourceManager.GetString("Verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        public static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkShop.
        /// </summary>
        public static string WorkShop {
            get {
                return ResourceManager.GetString("WorkShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can edit meter data only at english site version.
        /// </summary>
        public static string YouCanEditMeterDataOnlyAtEnglishSiteVersion {
            get {
                return ResourceManager.GetString("YouCanEditMeterDataOnlyAtEnglishSiteVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not pay this bill again.
        /// </summary>
        public static string YouCanNotPayThisBillAgain {
            get {
                return ResourceManager.GetString("YouCanNotPayThisBillAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no administrator rights!.
        /// </summary>
        public static string YouHaveNoAdministratorRights {
            get {
                return ResourceManager.GetString("YouHaveNoAdministratorRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter at least 1 utility usage.
        /// </summary>
        public static string YouMustEnterAtLeastOneUtilityUsage {
            get {
                return ResourceManager.GetString("YouMustEnterAtLeastOneUtilityUsage", resourceCulture);
            }
        }
    }
}
