//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownUtilityBillSystemV2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TownUtilityBillSystemV2.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Thomas Thune Andersen, Chairman of the Board of Directors, said: “DONG was originally short for Danish Oil and Natural Gas. With our profound strategic 
        ///transformation and the divestment of our upstream oil and gas business, this is no longer who we are. Therefore, now is the right time to change our name..
        /// </summary>
        public static string AboutData_ChairmanСitation {
            get {
                return ResourceManager.GetString("AboutData_ChairmanСitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the 6th of November 2017.
        /// </summary>
        public static string AboutData_ChangeNameDate {
            get {
                return ResourceManager.GetString("AboutData_ChangeNameDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7th of August 2017..
        /// </summary>
        public static string AboutData_FirstReleaseDate {
            get {
                return ResourceManager.GetString("AboutData_FirstReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has changed name to.
        /// </summary>
        public static string AboutData_HasChangedNameTo {
            get {
                return ResourceManager.GetString("AboutData_HasChangedNameTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is a web application that helps to manage by the data for the town utility services such as the electricity, the water, the heating and the gas. Also it operates by the customer bill system..
        /// </summary>
        public static string AboutData_IsAWebAppThatHelps {
            get {
                return ResourceManager.GetString("AboutData_IsAWebAppThatHelps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is one of Northern Europe&apos;s leading energy groups and is headquartered in Denmark. Around 6,500 ambitious employees develop, construct and operate offshore wind farms, generate power and heat from our power	stations as well as supply and trade in energy to wholesale, business and residential customers. In addition, we produce oil and gas, and a process has been initiated to divest this business unit. The continuing part of the Group has approx 6,100 employees
        ///and generated a revenue in 2016 of DKK 61 billi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutData_IsOneOfNorthernEurope {
            get {
                return ResourceManager.GetString("AboutData_IsOneOfNorthernEurope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first release of the App was on the.
        /// </summary>
        public static string AboutData_TheFirstRelease {
            get {
                return ResourceManager.GetString("AboutData_TheFirstRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All meter types.
        /// </summary>
        public static string AllMeterTypes {
            get {
                return ResourceManager.GetString("AllMeterTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All news.
        /// </summary>
        public static string AllNews {
            get {
                return ResourceManager.GetString("AllNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Utilities.
        /// </summary>
        public static string AllUtilities {
            get {
                return ResourceManager.GetString("AllUtilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All utility meters.
        /// </summary>
        public static string AllUtilityMeters {
            get {
                return ResourceManager.GetString("AllUtilityMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to home page.
        /// </summary>
        public static string BackToHomePage {
            get {
                return ResourceManager.GetString("BackToHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to previous page.
        /// </summary>
        public static string BackToPreviousPage {
            get {
                return ResourceManager.GetString("BackToPreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bills.
        /// </summary>
        public static string Bills {
            get {
                return ResourceManager.GetString("Bills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        public static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator on-line.
        /// </summary>
        public static string CalculatorOnLine {
            get {
                return ResourceManager.GetString("CalculatorOnLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check utility name.
        /// </summary>
        public static string CheckUtilityName {
            get {
                return ResourceManager.GetString("CheckUtilityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the next facility.
        /// </summary>
        public static string ChooseNextFacility {
            get {
                return ResourceManager.GetString("ChooseNextFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match.
        /// </summary>
        public static string ConfirmPasswordWarning {
            get {
                return ResourceManager.GetString("ConfirmPasswordWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the new meter.
        /// </summary>
        public static string CreateNewMeter {
            get {
                return ResourceManager.GetString("CreateNewMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the new meter type.
        /// </summary>
        public static string CreateNewMeterType {
            get {
                return ResourceManager.GetString("CreateNewMeterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the new utility.
        /// </summary>
        public static string CreateNewUtility {
            get {
                return ResourceManager.GetString("CreateNewUtility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONG Energy.
        /// </summary>
        public static string DongEnergy {
            get {
                return ResourceManager.GetString("DongEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit utility parameters.
        /// </summary>
        public static string EditUtilityParameters {
            get {
                return ResourceManager.GetString("EditUtilityParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity.
        /// </summary>
        public static string Electricity {
            get {
                return ResourceManager.GetString("Electricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        public static string EnterValidEmail {
            get {
                return ResourceManager.GetString("EnterValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid phone.
        /// </summary>
        public static string EnterValidPhone {
            get {
                return ResourceManager.GetString("EnterValidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is required.
        /// </summary>
        public static string FieldIsRequired {
            get {
                return ResourceManager.GetString("FieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find meter by address.
        /// </summary>
        public static string FindMeterByAddress {
            get {
                return ResourceManager.GetString("FindMeterByAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find meter by details.
        /// </summary>
        public static string FindMeterByDetails {
            get {
                return ResourceManager.GetString("FindMeterByDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find meters by details.
        /// </summary>
        public static string FindMetersByDetails {
            get {
                return ResourceManager.GetString("FindMetersByDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat/Part.
        /// </summary>
        public static string FlatPart {
            get {
                return ResourceManager.GetString("FlatPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For additional information, please contact.
        /// </summary>
        public static string ForAdditionalInfoPleaseContact {
            get {
                return ResourceManager.GetString("ForAdditionalInfoPleaseContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        public static string Found {
            get {
                return ResourceManager.GetString("Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found 1 meter.
        /// </summary>
        public static string FoundOneMeter {
            get {
                return ResourceManager.GetString("FoundOneMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas.
        /// </summary>
        public static string Gas {
            get {
                return ResourceManager.GetString("Gas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heating.
        /// </summary>
        public static string Heating {
            get {
                return ResourceManager.GetString("Heating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Higher price.
        /// </summary>
        public static string HigherPrice {
            get {
                return ResourceManager.GetString("HigherPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt.
        /// </summary>
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than.
        /// </summary>
        public static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log_in.
        /// </summary>
        public static string Log_In {
            get {
                return ResourceManager.GetString("Log_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginForApp {
            get {
                return ResourceManager.GetString("LoginForApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in the system.
        /// </summary>
        public static string LogInSystem {
            get {
                return ResourceManager.GetString("LogInSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters.
        /// </summary>
        public static string Meters {
            get {
                return ResourceManager.GetString("Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter types.
        /// </summary>
        public static string MeterTypes {
            get {
                return ResourceManager.GetString("MeterTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter types.
        /// </summary>
        public static string MeterTypesLowerCase {
            get {
                return ResourceManager.GetString("MeterTypesLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New value.
        /// </summary>
        public static string NewValue {
            get {
                return ResourceManager.GetString("NewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No any meter is found.
        /// </summary>
        public static string NoAnyMeterIsFound {
            get {
                return ResourceManager.GetString("NoAnyMeterIsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ørsted.
        /// </summary>
        public static string Orsted {
            get {
                return ResourceManager.GetString("Orsted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other utilities.
        /// </summary>
        public static string OtherUtilities {
            get {
                return ResourceManager.GetString("OtherUtilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay on-line.
        /// </summary>
        public static string PayOnLine {
            get {
                return ResourceManager.GetString("PayOnLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per.
        /// </summary>
        public static string Per {
            get {
                return ResourceManager.GetString("Per", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, log in or register.
        /// </summary>
        public static string PleaseLogInOrRegister {
            get {
                return ResourceManager.GetString("PleaseLogInOrRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more....
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string RegisterAsNewUser {
            get {
                return ResourceManager.GetString("RegisterAsNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        public static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date.
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search filter.
        /// </summary>
        public static string SearchFilter {
            get {
                return ResourceManager.GetString("SearchFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all meters.
        /// </summary>
        public static string ShowAllMeters {
            get {
                return ResourceManager.GetString("ShowAllMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Meter Types.
        /// </summary>
        public static string ShowAllMeterTypes {
            get {
                return ResourceManager.GetString("ShowAllMeterTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all utilities.
        /// </summary>
        public static string ShowAllUtilities {
            get {
                return ResourceManager.GetString("ShowAllUtilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Found Meters.
        /// </summary>
        public static string ShowFoundMeters {
            get {
                return ResourceManager.GetString("ShowFoundMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show some meters.
        /// </summary>
        public static string ShowSomeMeters {
            get {
                return ResourceManager.GetString("ShowSomeMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the news.
        /// </summary>
        public static string ShowTheNews {
            get {
                return ResourceManager.GetString("ShowTheNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some random meters.
        /// </summary>
        public static string SomeRandomMeters {
            get {
                return ResourceManager.GetString("SomeRandomMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistic.
        /// </summary>
        public static string Statistic {
            get {
                return ResourceManager.GetString("Statistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total customers for this utility.
        /// </summary>
        public static string TotalCustomersForThisUtility {
            get {
                return ResourceManager.GetString("TotalCustomersForThisUtility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total quantity.
        /// </summary>
        public static string TotalQuantity {
            get {
                return ResourceManager.GetString("TotalQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town.
        /// </summary>
        public static string Town {
            get {
                return ResourceManager.GetString("Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town Utility Bill System.
        /// </summary>
        public static string TownUtilityBillSystem {
            get {
                return ResourceManager.GetString("TownUtilityBillSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage for standart price.
        /// </summary>
        public static string UsageForStandartPrice {
            get {
                return ResourceManager.GetString("UsageForStandartPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        public static string Utilities {
            get {
                return ResourceManager.GetString("Utilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility.
        /// </summary>
        public static string Utility {
            get {
                return ResourceManager.GetString("Utility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility meters.
        /// </summary>
        public static string UtilityMeters {
            get {
                return ResourceManager.GetString("UtilityMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string ValueMustBeAtLeastCharactersLong {
            get {
                return ResourceManager.GetString("ValueMustBeAtLeastCharactersLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be bigger than {1}..
        /// </summary>
        public static string ValueMustBeBiggerThan {
            get {
                return ResourceManager.GetString("ValueMustBeBiggerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be bigger than 0..
        /// </summary>
        public static string ValueMustBeBiggerThanZero {
            get {
                return ResourceManager.GetString("ValueMustBeBiggerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must habe from {2} to {1} characters long..
        /// </summary>
        public static string ValueMustHaveFromToCharactersLong {
            get {
                return ResourceManager.GetString("ValueMustHaveFromToCharactersLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification date.
        /// </summary>
        public static string VarificationDate {
            get {
                return ResourceManager.GetString("VarificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification period.
        /// </summary>
        public static string VarificationPeriod {
            get {
                return ResourceManager.GetString("VarificationPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varification.
        /// </summary>
        public static string Verification {
            get {
                return ResourceManager.GetString("Verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        public static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
    }
}
