//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownUtilityBillSystemV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUILDING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BUILDING()
        {
            this.ADDRESSes = new HashSet<ADDRESS>();
            this.FLAT_PART = new HashSet<FLAT_PART>();
        }
    
        public int ID { get; set; }
        public string NUMBER { get; set; }
        public Nullable<float> SQUARE { get; set; }
        public int STREET_ID { get; set; }
        public Nullable<int> IMAGE_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADDRESS> ADDRESSes { get; set; }
        public virtual IMAGE_BUILDING IMAGE_BUILDING { get; set; }
        public virtual STREET STREET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FLAT_PART> FLAT_PART { get; set; }
    }
}
