//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownUtilityBillSystemV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class METER_ITEM
    {
        public int ID { get; set; }
        public int METER_ID { get; set; }
        public System.DateTime DATE { get; set; }
        public float VALUE { get; set; }
    
        public virtual METER METER { get; set; }
    }
}
