//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownUtilityBillSystemV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class METER_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public METER_TYPE()
        {
            this.METERs = new HashSet<METER>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public int VARIFICATION_PERIOD_YEARS { get; set; }
        public int UTILITY_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<METER> METERs { get; set; }
        public virtual UTILITY UTILITY { get; set; }
    }
}
