//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownUtilityBillSystemV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWS_TITLE
    {
        public int ID { get; set; }
        public string TITLE { get; set; }
        public string LANGUAGE { get; set; }
        public int NEWS_ID { get; set; }
    
        public virtual NEWS NEWS { get; set; }
    }
}
