//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownUtilityBillSystemV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NEWS()
        {
            this.NEWS_CHAPTER = new HashSet<NEWS_CHAPTER>();
            this.NEWS_TITLE = new HashSet<NEWS_TITLE>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public System.DateTime DATE { get; set; }
        public Nullable<int> IMAGE_ID { get; set; }
    
        public virtual IMAGE_NEWS IMAGE_NEWS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NEWS_CHAPTER> NEWS_CHAPTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NEWS_TITLE> NEWS_TITLE { get; set; }
    }
}
