//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownUtilityBillSystemV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT
    {
        public int ID { get; set; }
        public string NUMBER { get; set; }
        public decimal SUM { get; set; }
        public System.DateTime DATE { get; set; }
        public string NOTE { get; set; }
        public int ACCOUNT_ID { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
    }
}
