//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownUtilityBillSystemV2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

	public partial class TownUtilityBillSystemV2Entities : DbContext
	{
        public TownUtilityBillSystemV2Entities()
            : base("name=TownUtilityBillSystemV2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

		public virtual DbSet<ACCOUNT> ACCOUNTs { get; set; }
		public virtual DbSet<ADDRESS> ADDRESSes { get; set; }
		public virtual DbSet<BILL> BILLs { get; set; }
		public virtual DbSet<BUILDING> BUILDINGs { get; set; }
		public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
		public virtual DbSet<CUSTOMER_TYPE> CUSTOMER_TYPEs { get; set; }
		public virtual DbSet<FLAT_PART> FLAT_PARTs { get; set; }
		public virtual DbSet<IMAGE_BUILDING> IMAGE_BUILDINGs { get; set; }
		public virtual DbSet<IMAGE_NEWS> IMAGE_NEWS { get; set; }
		public virtual DbSet<IMAGE_UTILITY> IMAGE_UTILITYs { get; set; }
		public virtual DbSet<INDEX> INDEXes { get; set; }
		public virtual DbSet<METER> METERs { get; set; }
		public virtual DbSet<METER_ITEM> METER_ITEMs { get; set; }
		public virtual DbSet<METER_TYPE> METER_TYPEs { get; set; }
		public virtual DbSet<PAYMENT> PAYMENTs { get; set; }
		public virtual DbSet<STREET> STREETs { get; set; }
		public virtual DbSet<TEMPERATURE> TEMPERATUREs { get; set; }
		public virtual DbSet<TOWN> TOWNs { get; set; }
		public virtual DbSet<UNIT> UNITs { get; set; }
		public virtual DbSet<UTILITY> UTILITYs { get; set; }
		public virtual DbSet<NEWS> NEWS { get; set; }
		public virtual DbSet<NEWS_CHAPTER> NEWS_CHAPTERs { get; set; }
		public virtual DbSet<NEWS_TITLE> NEWS_TITLEs { get; set; }
	}
}
