//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownUtilityBillSystemV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTILITY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UTILITY()
        {
            this.METER_TYPE = new HashSet<METER_TYPE>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public decimal PRICE { get; set; }
        public Nullable<decimal> USAGEFORSTANDARTPRICE { get; set; }
        public Nullable<decimal> BIGUSAGEPRICE { get; set; }
        public int UNIT_ID { get; set; }
        public int IMAGE_ID { get; set; }
    
        public virtual IMAGE_UTILITY IMAGE_UTILITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<METER_TYPE> METER_TYPE { get; set; }
        public virtual UNIT UNIT { get; set; }
    }
}
