USE TOWN_UTILITY_BILL_SYSTEM_V2
GO

--DELETE FROM UTILITY
--DBCC CHECKIDENT ('TOWN_UTILITY_BILL_SYSTEM_V2.dbo.UTILITY',RESEED, 0)

--DELETE FROM METER_TYPE
--DBCC CHECKIDENT ('TOWN_UTILITY_BILL_SYSTEM_V2.dbo.METER_TYPE',RESEED, 0)

--DELETE FROM ACCOUNT
--DBCC CHECKIDENT ('TOWN_UTILITY_BILL_SYSTEM_V2.dbo.ACCOUNT',RESEED, 0)

--DELETE FROM [METER]
--DBCC CHECKIDENT ('TOWN_UTILITY_BILL_SYSTEM_V2.dbo.METER',RESEED, 0)

--DELETE FROM [IMAGEBUILDING]
--DBCC CHECKIDENT ('TOWN_UTILITY_BILL_SYSTEM_V2.dbo.IMAGEBUILDING',RESEED, 0)

--DELETE FROM [IMAGEUTILITY]
--DBCC CHECKIDENT ('TOWN_UTILITY_BILL_SYSTEM_V2.dbo.IMAGEUTILITY',RESEED, 0)

--DELETE FROM FLAT_PART
--DBCC CHECKIDENT ('TOWN_UTILITY_BILL_SYSTEM_V2.dbo.FLAT_PART',RESEED, 0)

--DELETE FROM BUILDING
--DBCC CHECKIDENT ('TOWN_UTILITY_BILL_SYSTEM_V2.dbo.BUILDING',RESEED, 0)


--DELETE FROM STREET
--DBCC CHECKIDENT ('TOWN_UTILITY_BILL_SYSTEM_V2.dbo.STREET',RESEED, 0)

--DELETE FROM TOWN
--DBCC CHECKIDENT ('TOWN_UTILITY_BILL_SYSTEM_V2.dbo.TOWN',RESEED, 0)

--DELETE FROM CUSTOMER_TYPE
--DBCC CHECKIDENT ('TOWN_UTILITY_BILL_SYSTEM_V2.dbo.CUSTOMER_TYPE',RESEED, 0)

--DELETE FROM CUSTOMER
--DBCC CHECKIDENT ('TOWN_UTILITY_BILL_SYSTEM_V2.dbo.CUSTOMER',RESEED, 0)

--DELETE FROM [ADDRESS]
--DBCC CHECKIDENT ('TOWN_UTILITY_BILL_SYSTEM_V2.dbo.ADDRESS',RESEED, 0)


--DELETE FROM TEMPERATURE
--DBCC CHECKIDENT ('TOWN_UTILITY_BILL_SYSTEM_V2.dbo.TEMPERATURE',RESEED, 0)

--DELETE FROM METER_ITEM
--DBCC CHECKIDENT ('TOWN_UTILITY_BILL_SYSTEM_V2.dbo.METER_ITEM',RESEED, 0)

--DELETE FROM BILL
--DBCC CHECKIDENT ('TOWN_UTILITY_BILL_SYSTEM_V2.dbo.BILL',RESEED, 0)

--DELETE FROM NEWS_CHAPTER
--DBCC CHECKIDENT ('TOWN_UTILITY_BILL_SYSTEM_V2.dbo.NEWS_CHAPTER',RESEED, 0)

--DELETE FROM NEWS_TITLE
--DBCC CHECKIDENT ('TOWN_UTILITY_BILL_SYSTEM_V2.dbo.NEWS_TITLE',RESEED, 0)

--DELETE FROM NEWS
--DBCC CHECKIDENT ('TOWN_UTILITY_BILL_SYSTEM_V2.dbo.NEWS',RESEED, 0)

--DELETE FROM IMAGENEWS
--DBCC CHECKIDENT ('TOWN_UTILITY_BILL_SYSTEM_V2.dbo.IMAGENEWS',RESEED, 0)


